apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ventas
  labels:
    app: backend-ventas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-ventas
  template:
    metadata:
      labels:
        app: backend-ventas
    spec:
      containers:
      - name: backend-ventas
        image: 889217351448.dkr.ecr.us-east-1.amazonaws.com/despachos-back-ventas:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
            env:
              - name: DB_ENDPOINT
                value: "despachos-db.cnletjr0vyhc.us-east-1.rds.amazonaws.com"

              - name: DB_PORT
                value: "3306"

              - name: DB_NAME
                value: "ventas"

              - name: DB_USERNAME
                value: "admin"

              - name: DB_PASSWORD
                value: "12345678"