name: Build Push Deploy EKS

on:
  push:
    branches:
      - main

env:
  ECR_BACK_DESPACHOS: despachos-back-despachos
  ECR_BACK_VENTAS: despachos-back-ventas
  ECR_FRONTEND: despachos-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR repositories if they do not exist
        run: |
          aws ecr describe-repositories --repository-names $ECR_BACK_DESPACHOS || aws ecr create-repository --repository-name $ECR_BACK_DESPACHOS
          aws ecr describe-repositories --repository-names $ECR_BACK_VENTAS || aws ecr create-repository --repository-name $ECR_BACK_VENTAS
          aws ecr describe-repositories --repository-names $ECR_FRONTEND || aws ecr create-repository --repository-name $ECR_FRONTEND

      - name: Build Backend Despachos
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_BACK_DESPACHOS }}:latest \
            ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO

      - name: Push Backend Despachos
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_BACK_DESPACHOS }}:latest

      - name: Build Backend Ventas
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_BACK_VENTAS }}:latest \
            ./back-Ventas_SpringBoot/Springboot-API-REST

      - name: Push Backend Ventas
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_BACK_VENTAS }}:latest

      - name: Build Frontend
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_FRONTEND }}:latest \
            ./front_despacho

      - name: Push Frontend
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_FRONTEND }}:latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Deploy Kubernetes
        run: |
          kubectl apply -f k8s/

      - name: Restart Deployments
        run: |
          kubectl rollout restart deployment/backend-despachos
          kubectl rollout restart deployment/backend-ventas
          kubectl rollout restart deployment/frontend